-- lib/presets.lua
-- Training Tools: Situation / Setup Practice Preset Library for Zen Mode

local Board = require("lib.board")
local constants = require("lib.constants")
local Queue = require("lib.queue")

local Presets = {}

Presets.categories = {
    { id = "tspin", name = "T-Spin Opening Setups" },
    { id = "pc",    name = "Perfect Clear Openings" },
    { id = "dig",   name = "Mid-game Digging & Downstacking" }
}

-- ASCII Grid format helper: 20 lines of 10 characters representing visible rows 21..40
-- '.' = Empty
-- 'X' = Garbage block
-- 'I','J','L','O','S','T','Z' = Specific mino types
local function parse_grid(ascii_str)
    local board = Board.new()
    local lines = {}
    for line in ascii_str:gmatch("[^\r\n]+") do
        -- Trim trailing whitespace or comments if any
        line = line:match("^%s*(.-)%s*$")
        if #line == 10 then
            table.insert(lines, line)
        end
    end

    -- We expect 20 rows corresponding to rows 21..40
    local start_row = 40 - #lines + 1
    for r_idx, line in ipairs(lines) do
        local target_row = start_row + r_idx - 1
        for col = 1, 10 do
            local char = line:sub(col, col)
            if char ~= "." then
                Board.set_cell(board, target_row, col, char)
            end
        end
    end
    return board
end

Presets.list = {
    -- ─── T-Spin Opening Setups & Free Play ─────────────────────────────────
    {
        id = "empty_standard",
        category = "tspin",
        name = "Standard Free Play",
        subtitle = "Clean Grid Practice",
        description = "Start with a clean empty playfield and standard randomizer queue.",
        queue = nil,
        ascii = nil
    },
    {
        id = "dt_cannon",
        category = "tspin",
        name = "DT Cannon",
        subtitle = "Double Triple Cannon Opening",
        description = "Classic setup featuring a T-Slot for T-Spin Double followed immediately by T-Spin Triple.",
        queue = {"T", "T", "I", "J", "L", "O", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...L......
...L......
LL.L.XXXXX
LL...XXXXX
LL..XXXXXX
LL.XXXXXXX
LL.XXXXXXX
]]
    },
    {
        id = "tki_3",
        category = "tspin",
        name = "TKI 3 Opening",
        subtitle = "Flat T-Spin Double Opening",
        description = "Extremely versatile 1st-bag T-Spin Double opening with clean follow-up routes.",
        queue = {"T", "J", "L", "I", "O", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...X.XXXXX
XXX.XXXXXX
XXX.XXXXXX
]]
    },
    {
        id = "imperial_cross",
        category = "tspin",
        name = "Imperial Cross",
        subtitle = "Double T-Spin Cross Overhang",
        description = "Advanced T-Spin setup featuring an intersecting cross slot for back-to-back T-Spins.",
        queue = {"T", "T", "I", "J", "L", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...Z......
..ZZ.XXXXX
..Z..XXXXX
XXXX.XXXXX
XXXX.XXXXX
]]
    },

    -- ─── Perfect Clear Openings ──────────────────────────────────────────────
    {
        id = "pc_pco",
        category = "pc",
        name = "PCO (JLSZ Setup)",
        subtitle = "1st Bag Perfect Clear Opening",
        description = "Standard 1st Perfect Clear setup. Clear the 4-line height grid for a 100% board wipe!",
        queue = {"I", "J", "L", "O", "T", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
JJ.LL..OO.
J...L..OO.
ZZ.SS.IIII
.ZZSS.IIII
]]
    },
    {
        id = "pc_grace",
        category = "pc",
        name = "Grace System 4-Line PC",
        subtitle = "4-Line Finish Practice",
        description = "Practice placing the final key pieces to trigger a flawless 4-line Perfect Clear.",
        queue = {"O", "I", "J", "L", "T"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
XXXX....XX
XXXX...XXX
XXXX..XXXX
XXXX..XXXX
]]
    },

    -- ─── Mid-game Digging & Downstacking ─────────────────────────────────────
    {
        id = "dig_shallow",
        category = "dig",
        name = "Shallow Garbage Dig",
        subtitle = "4-Row Garbage Downstack",
        description = "Practice digging through 4 rows of staggered garbage holes while maintaining stack balance.",
        queue = {"I", "T", "J", "L", "O", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...S......
..SS.J....
XXXX.XXXXX
XXXXXX.XXX
XX.XXXXXXX
XXXXX.XXXX
]]
    },
    {
        id = "dig_deep_shaft",
        category = "dig",
        name = "Deep Garbage Shaft",
        subtitle = "8-Row Narrow Downstack",
        description = "Deep single-column garbage hole on the far left. Downstack quickly before topping out!",
        queue = {"I", "J", "L", "O", "T", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
.XXXXXXXXX
.XXXXXXXXX
.XXXXXXXXX
.XXXXXXXXX
.XXXXXXXXX
.XXXXXXXXX
.XXXXXXXXX
.XXXXXXXXX
]]
    },
    {
        id = "dig_spike_defense",
        category = "dig",
        name = "Spike Defense Dig",
        subtitle = "12-Row High Pressure Dig",
        description = "High-pressure survival scenario! Stack is 12 rows tall with messy garbage beneath.",
        queue = {"T", "I", "J", "L", "O", "S", "Z"},
        ascii = [[
..........
..........
..........
..........
..........
..........
..........
..........
.XXXXXXXXX
.XXXXXXXXX
XX.XXXXXXX
XXXX.XXXXX
XXXXXX.XXX
XXXXX.XXXX
XX.XXXXXXX
XXX.XXXXXX
XXXXX.XXXX
XXXX.XXXXX
XXXXXX.XXX
XX.XXXXXXX
]]
    }
}

function Presets.getByCategory(cat_id)
    local results = {}
    for _, item in ipairs(Presets.list) do
        if item.category == cat_id then
            table.insert(results, item)
        end
    end
    return results
end

function Presets.get(preset_id)
    for _, item in ipairs(Presets.list) do
        if item.id == preset_id then
            return item
        end
    end
    return nil
end

function Presets.build_board(preset)
    if not preset or not preset.ascii then
        return Board.new()
    end
    return parse_grid(preset.ascii)
end

return Presets
